In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width: 98% !important }</style>"))

In [2]:
from utilities import *
from models import *

import joblib

In [3]:
ble = read_ble('../Data/ble.csv')

In [4]:
coor = None

In [5]:
def reg_impute(data):
    for s in scanners:
        dx = coor[0] - ble[s]['X']
        dy = coor[1] - ble[s]['Y']
        d = np.sqrt(np.square(dy) + np.square(dx))
        reg = joblib.load('../Models/linear_distance_models/{}.joblib'.format(s))
        ss = pd.Series(reg.predict(d.reshape((-1, 1))))
        data[s].fillna(ss, inplace=True)

In [6]:
model = MLPRegressor(model_type='special')
model.model.fit(np.array([[0] * 17]), np.array([[0, 0]]))
model.model.load_weights('../Models/MLP_Regression_Rolling_FFill_MinMax_ExtraTest_LinearDistanceModel.h5')

Train on 1 samples
1/1 [==============================] - 1s 725ms/sample - loss: 0.6618 - mae: 0.0000e+00 - mse: 0.0000e+00


In [7]:
client = InfluxDBClient()

In [8]:
data = client.retrieveData(seconds=3, beacon="0117C55D14E4")

In [9]:
data = format_data(data)

In [10]:
data[scanners] = min_max_scaling(data[scanners])

In [11]:
data = data.rolling(15, min_periods=1).mean().reset_index()

In [12]:
data = data.ffill()

In [13]:
data

index  C400A2E19293  CD4533FFC0E1  D2B6503554D7  \
0  2019-12-19 03:26:27.402000+00:00           NaN           NaN           NaN   
1  2019-12-19 03:26:27.511000+00:00           NaN           NaN           NaN   
2  2019-12-19 03:26:27.632000+00:00           NaN      0.383333           NaN   
3  2019-12-19 03:26:27.737000+00:00      0.133333      0.383333           NaN   
4  2019-12-19 03:26:27.749000+00:00      0.133333      0.383333           NaN   
5  2019-12-19 03:26:27.813000+00:00      0.133333      0.383333           NaN   
6  2019-12-19 03:26:27.912000+00:00      0.133333      0.383333           NaN   
7  2019-12-19 03:26:27.977000+00:00      0.133333      0.383333           NaN   
8  2019-12-19 03:26:27.993000+00:00      0.133333      0.383333           NaN   
9  2019-12-19 03:26:28.287000+00:00      0.133333      0.383333           NaN   
10 2019-12-19 03:26:28.492000+00:00      0.133333      0.383333           NaN   
11 2019-12-19 03:26:28.496000+00:00      0.133333      0.383333           NaN   
12 2019-12-19 03:26:28.579000+00:00      0.133333      0.383333           NaN   
13 2019-12-19 03:26:28.628000+00:00      0.133333      0.383333           NaN   
14 2019-12-19 03:26:28.653000+00:00      0.133333      0.405556           NaN   
15 2019-12-19 03:26:28.739000+00:00      0.133333      0.405556           NaN   
16 2019-12-19 03:26:28.740000+00:00      0.133333      0.405556           NaN   
17 2019-12-19 03:26:28.741000+00:00      0.133333      0.416667           NaN   
18 2019-12-19 03:26:28.858000+00:00      0.133333      0.416667           NaN   
19 2019-12-19 03:26:28.859000+00:00      0.133333      0.416667           NaN   
20 2019-12-19 03:26:28.953000+00:00      0.133333      0.416667           NaN   
21 2019-12-19 03:26:28.975000+00:00      0.133333      0.416667           NaN   
22 2019-12-19 03:26:28.976000+00:00      0.133333      0.450000           NaN   
23 2019-12-19 03:26:29.085000+00:00      0.133333      0.450000           NaN   
24 2019-12-19 03:26:29.097000+00:00      0.133333      0.450000           NaN   
25 2019-12-19 03:26:29.312000+00:00      0.133333      0.450000           NaN   
26 2019-12-19 03:26:29.314000+00:00      0.133333      0.450000           NaN   
27 2019-12-19 03:26:29.417000+00:00      0.133333      0.450000           NaN   
28 2019-12-19 03:26:29.652000+00:00      0.133333      0.450000           NaN   
29 2019-12-19 03:26:29.654000+00:00      0.133333      0.450000           NaN   
30 2019-12-19 03:26:29.672000+00:00      0.133333      0.450000           NaN   
31 2019-12-19 03:26:29.851000+00:00      0.133333      0.450000           NaN   
32 2019-12-19 03:26:29.968000+00:00      0.133333      0.450000           NaN   
33 2019-12-19 03:26:29.969000+00:00      0.133333      0.450000           NaN   
34 2019-12-19 03:26:30.009000+00:00      0.166667      0.450000           NaN   
35 2019-12-19 03:26:30.045000+00:00      0.166667      0.450000           NaN   
36 2019-12-19 03:26:30.075000+00:00      0.166667      0.450000           NaN   
37 2019-12-19 03:26:30.153000+00:00      0.166667      0.450000           NaN   
38 2019-12-19 03:26:30.203000+00:00      0.166667      0.450000           NaN   
39 2019-12-19 03:26:30.208000+00:00      0.166667      0.450000           NaN   

    DB8B36A69C56  DD697EA75B68  DF231643E227  E13B805C6CB0  E43355CA8B96  \
0            NaN           NaN           NaN           NaN           NaN   
1       0.433333           NaN           NaN           NaN           NaN   
2       0.433333           NaN           NaN           NaN           NaN   
3       0.433333           NaN           NaN           NaN           NaN   
4       0.433333           NaN           NaN           NaN           NaN   
5       0.433333           NaN           NaN           NaN           NaN   
6       0.433333           NaN           NaN           NaN           NaN   
7       0.433333           NaN           NaN           NaN           NaN   
8       0.433333        

In [14]:
if coor is None:
    data = data.fillna(0)
else:
    reg_impute(data)

In [15]:
coor = model.predict(data[scanners]).mean(axis=0)

In [16]:
np.expand_dims(coor, axis=0)

array([[19.932127, 12.176935]], dtype=float32)

In [17]:
coor

array([19.932127, 12.176935], dtype=float32)

In [18]:
data

index  C400A2E19293  CD4533FFC0E1  D2B6503554D7  \
0  2019-12-19 03:26:27.402000+00:00      0.000000      0.000000           0.0   
1  2019-12-19 03:26:27.511000+00:00      0.000000      0.000000           0.0   
2  2019-12-19 03:26:27.632000+00:00      0.000000      0.383333           0.0   
3  2019-12-19 03:26:27.737000+00:00      0.133333      0.383333           0.0   
4  2019-12-19 03:26:27.749000+00:00      0.133333      0.383333           0.0   
5  2019-12-19 03:26:27.813000+00:00      0.133333      0.383333           0.0   
6  2019-12-19 03:26:27.912000+00:00      0.133333      0.383333           0.0   
7  2019-12-19 03:26:27.977000+00:00      0.133333      0.383333           0.0   
8  2019-12-19 03:26:27.993000+00:00      0.133333      0.383333           0.0   
9  2019-12-19 03:26:28.287000+00:00      0.133333      0.383333           0.0   
10 2019-12-19 03:26:28.492000+00:00      0.133333      0.383333           0.0   
11 2019-12-19 03:26:28.496000+00:00      0.133333      0.383333           0.0   
12 2019-12-19 03:26:28.579000+00:00      0.133333      0.383333           0.0   
13 2019-12-19 03:26:28.628000+00:00      0.133333      0.383333           0.0   
14 2019-12-19 03:26:28.653000+00:00      0.133333      0.405556           0.0   
15 2019-12-19 03:26:28.739000+00:00      0.133333      0.405556           0.0   
16 2019-12-19 03:26:28.740000+00:00      0.133333      0.405556           0.0   
17 2019-12-19 03:26:28.741000+00:00      0.133333      0.416667           0.0   
18 2019-12-19 03:26:28.858000+00:00      0.133333      0.416667           0.0   
19 2019-12-19 03:26:28.859000+00:00      0.133333      0.416667           0.0   
20 2019-12-19 03:26:28.953000+00:00      0.133333      0.416667           0.0   
21 2019-12-19 03:26:28.975000+00:00      0.133333      0.416667           0.0   
22 2019-12-19 03:26:28.976000+00:00      0.133333      0.450000           0.0   
23 2019-12-19 03:26:29.085000+00:00      0.133333      0.450000           0.0   
24 2019-12-19 03:26:29.097000+00:00      0.133333      0.450000           0.0   
25 2019-12-19 03:26:29.312000+00:00      0.133333      0.450000           0.0   
26 2019-12-19 03:26:29.314000+00:00      0.133333      0.450000           0.0   
27 2019-12-19 03:26:29.417000+00:00      0.133333      0.450000           0.0   
28 2019-12-19 03:26:29.652000+00:00      0.133333      0.450000           0.0   
29 2019-12-19 03:26:29.654000+00:00      0.133333      0.450000           0.0   
30 2019-12-19 03:26:29.672000+00:00      0.133333      0.450000           0.0   
31 2019-12-19 03:26:29.851000+00:00      0.133333      0.450000           0.0   
32 2019-12-19 03:26:29.968000+00:00      0.133333      0.450000           0.0   
33 2019-12-19 03:26:29.969000+00:00      0.133333      0.450000           0.0   
34 2019-12-19 03:26:30.009000+00:00      0.166667      0.450000           0.0   
35 2019-12-19 03:26:30.045000+00:00      0.166667      0.450000           0.0   
36 2019-12-19 03:26:30.075000+00:00      0.166667      0.450000           0.0   
37 2019-12-19 03:26:30.153000+00:00      0.166667      0.450000           0.0   
38 2019-12-19 03:26:30.203000+00:00      0.166667      0.450000           0.0   
39 2019-12-19 03:26:30.208000+00:00      0.166667      0.450000           0.0   

    DB8B36A69C56  DD697EA75B68  DF231643E227  E13B805C6CB0  E43355CA8B96  \
0       0.000000         0.000      0.000000      0.000000      0.000000   
1       0.433333         0.000      0.000000      0.000000      0.000000   
2       0.433333         0.000      0.000000      0.000000      0.000000   
3       0.433333         0.000      0.000000      0.000000      0.000000   
4       0.433333         0.000      0.000000      0.000000      0.000000   
5       0.433333         0.000      0.000000      0.000000      0.000000   
6       0.433333         0.000      0.000000      0.000000      0.000000   
7       0.433333         0.000      0.000000      0.000000      0.000000   
8       0.433333        

In [19]:
if coor is None:
    data = data.fillna(0)
else:
    reg_impute(data)

In [20]:
coor = model.predict(data[scanners]).mean(axis=0)

In [21]:
coor

array([19.932127, 12.176935], dtype=float32)